### PR TITLE
fix: add type declaration file

### LINKED ISSUE #9: TypeScript types declaration file
This npm package needs a TypeScript types declaration file so that developers who enjoy writing with TS can use it with this package and have a better development experience. Would you like me to write one?

### PR DESCRIPTION
**Pull request by geopic**
(resolves #9)

Here is the `index.d.ts` file. I've had to type some values as `any` however (so type information is not available for those values), but if you let me know what the `builder` parameter value is supposed to be in some functions (as if what is its type) then I can work with that and try to replace the `any` types. Any corrections you'd like for me to make as well, don't hesitate to let me know.

EDIT: I can add a semantic commit message too :sweat_smile: Didn't know that was required

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { Model, ModelClass } from 'objection';
+
+declare module 'objection-graphql-relay' {
+  export function idWrapper(modelName?: string): (parent: Model) => Promise<string>;
+  export function fromGlobalId(modelName?: string, globalId?: string): string;
+  export function singleRelationshipWrapper(relationshipName: string): Promise<string>;
+  export function connectionWrapper(field: string | object): Promise<object>;
```
Comment (sammarks) [inline index.d.ts]: Probably better instead of just typing to `object` to create the interface representing the possible configuration values. Something like this:

```typescript
interface ConnectionWrapperResults {
  results: any[]
  total: number
}
type ConnectionWrapperField = string | any[] | ConnectionWrapperResults
interface Edge {
  cursor: string
  node: Model
}
interface Connection {
  pageInfo {
    hasPreviousPage: boolean
    hasNextPage: boolean
  }
  edges: Edge[]
  totalCount: number
}

export function connectionWrapper(field: ConnectionWrapperField): Connection
```

File: index.d.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+  export function pagedRelationQuery(instance: ModelClass<Model>, field: string | object, first: number, after: number, extraFilter?: (builder: any) => object, orderBy?: (builder: any) => object): Promise<object>;
```
Comment (sammarks) [inline index.d.ts]: `builder` is an instance of `Objection.QueryBuilder` - The return value is also `Promise<ConnectionWrapperResults>` instead of `Promise<object>` (you can use the `ConnectionWrapperResults` type from above).

File: index.d.ts [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+  export function range(first?: number, after?: number, deferred?: object): Promise<any>;
```
Comment (sammarks) [inline index.d.ts]: Deferred is `Promise<QueryBuilder>`, and all of the arguments are required. The return value is `(builder: QueryBuilder) => void` instead of a promise.

File: index.d.ts [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+  export function relayModel(ModelClass: ModelClass<Model>): ModelClass<Model>;
```
Comment (sammarks) [inline index.d.ts]: I would type this generically so the types are preserved instead of resorting back to the `Objection.Model` type:

```typescript
export function relayModel<T extends ModelClass<Model>>(ModelClass: T): T
```

Not sure if that generic is too strict as I haven't used it in that format before, but worth a shot.

File: index.d.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+import { Model, ModelClass } from 'objection';
+
+declare module 'objection-graphql-relay' {
+  export function idWrapper(modelName?: string): (parent: Model) => Promise<string>;
+  export function fromGlobalId(modelName?: string, globalId?: string): string;
```
Comment (sammarks) [inline index.d.ts]: Parameters here are both required.

File: index.d.ts [hunk 6]
```diff
@@ -0,0 +1,11 @@
+import { Model, ModelClass } from 'objection';
+
+declare module 'objection-graphql-relay' {
+  export function idWrapper(modelName?: string): (parent: Model) => Promise<string>;
```
Comment (sammarks) [inline index.d.ts]: `modelName` parameter is required

**Review by sammarks — CHANGES_REQUESTED** [review]
Thanks for the PR! Made some comments where some of the types were incorrect. Make sure also to add `index.d.ts` to the `files` array inside `package.json` if it's not in there already (or if there isn't anything in there already I guess you can just leave it alone).

I would also update the PR title to be something like `fix: add type annotations` (probably wouldn't categorize it as a feature per-se).

File: index.d.ts [hunk 7]
```diff
@@ -0,0 +1,11 @@
...
+  export function fromGlobalId(modelName?: string, globalId?: string): string;
+  export function singleRelationshipWrapper(relationshipName: string): Promise<string>;
```
[the remark this answers is not in the document]
Comment (geopic) [reply index.d.ts]: Can you go into more detail on the 'GraphQL resolver'? What specifically is it (as in what exported value from `graphql`, or `graphql-relay`...)?

[the remark this answers is not in the document]
Comment (sammarks) [reply index.d.ts]: You’ll want to check out the [GraphQL Documentation](https://graphql.org) and the [JS GraphQL client](https://github.com/graphql/graphql-js) for more info on resolvers.

**Comment by geopic** [comment]
Hope I have got `singleRelationshipWrapper` right, let me know if it is incorrect. I'll squash commits when the PR is finalised

**Comment by sammarks** [comment]
No worries I went ahead and squashed it. Thanks for the contribution!
